### ISSUE TITLE
UnicodeEncodeError in similarity.py

### ISSUE THREAD

**Issue by fdemmer** [thisfred/autoqueue#1]
awesome plugin, thank you!

getting a unicode error with current master (a4fa0bc)

```
Get similar tracks for: mötley crüe - kickstart my heart
Error handler received: (DBusException(dbus.String(u'Traceback (most recent call last):\n
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n
  File "/usr/lib/pymodules/python2.7/autoqueue/similarity.py", line 878, in get_ordered_similar_tracks\n
    str(artist_name), str(title))\n
  File "/usr/lib/pymodules/python2.7/autoqueue/similarity.py", line 797, in get_ordered_similar_tracks\n
    artist_name, title))\n
UnicodeEncodeError: \'ascii\' codec can\'t encode character u\'\\xf6\' in position 37: ordinal not in range(128)\n'),),), {}
```

**Comment by thisfred** [comment]
I'm so sorry I haven't seen this bug report earlier. Must have gotten lost in the deluge of github notifications. I'm ashamed to ask, but are you still having this issue with current master, that you know?

**Comment by fdemmer** [comment]
i don't know. with the advent of spotify my quodlibet/autoqueue usage has ended a few years ago. thanks for asking though!
